### ISSUE TITLE
Supabase causes entire program to need internet

### ISSUE THREAD

**Issue by gwodny** [gopher-motorsports/gopher-vision#12]
gopher-vision crashes without internet now. This is particularily an issue for trackside, where the plan is to have a router to connect the hosting computer and other laptops, but will not have internet most likely.

**Comment by gwodny** [comment]
This also means internet is required for using the database. Would it be better to have a dropdown of local preset files instead/in addition? Mainly for trackside again.

**Comment by MX0416** [comment]
Yeah, that's the plan, Alex said the same thing, so I'm trying to think of a way to do local preset dropdown without having the user select a file/folder somehow.

**Comment by gwodny** [comment]
It needs a network, but not necessarily internet. That still works fine on the router with no internet connection I've been testing the trackside stuff with

**Comment by MX0416** [comment]
ah ok I see

**Comment by gwodny** [comment]
I'm just going to wrap the supabase functions in try blocks for now so they don't crash the program.
